!includeurl https://raw.githubusercontent.com/cop-pilot-eu/workflows-uml/refs/heads/main/templates/palette.puml
!includeurl https://raw.githubusercontent.com/cop-pilot-eu/workflows-uml/refs/heads/main/templates/theme.puml

' =====================
' COP-PILOT Components
' =====================

actor "Vertical\nEnd User" as VertEndUser #000000
actor "Infra.\nProvider" as InfPrv #000000
actor "Service\nProvider" as SvcPrv #000000
actor "Platform\nAdmin" as PltAdmin #000000

COP_PILOT_BOX_OUTER("Central COP-PILOT Platform")

    COP_PILOT_BOX_WITH_LOGO_INNER("Business\nPortal (BP)")
        COP_PILOT_SERVICE("LLM")
        COP_PILOT_SERVICE("Web")
        COP_PILOT_SERVICE("Cart")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    COP_PILOT_BOX_WITH_LOGO_INNER("Intent\nPlatform (IntP)")
        COP_PILOT_SERVICE("Intent Platform\nBackend")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    COP_PILOT_BOX_WITH_LOGO_INNER("End-to-End Service\nOrchestrator (ESO)")
        COP_PILOT_SERVICE("ESO\nPortal")
        COP_PILOT_SERVICE("ESO\nBackend")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    COP_PILOT_BOX_WITH_LOGO_INNER("Secure Integration\nFabric (SIF)")
        COP_PILOT_SERVICE("SIF\nController")
        COP_PILOT_SERVICE("SIF Client\nCentral")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

END_COP_PILOT_BOX_OUTER()

REMOTE_INFRA_BOX("Remote COP-PILOT Cluster")
    COP_PILOT_BOX_WITH_LOGO_INNER("SIF")
        COP_PILOT_SERVICE("SIF Client\nRemote")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    COP_PILOT_BOX_WITH_LOGO_INNER("Domain\nOrchestrator (DO)")
        COP_PILOT_SERVICE("DO\nPortal")
        COP_PILOT_SERVICE("DO\nBackend")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    COP_PILOT_BOX_WITH_LOGO_INNER("Data\nManagement (DM)")
        COP_PILOT_SERVICE("DM\nPortal")
        COP_PILOT_SERVICE("DM\nBackend")
    END_COP_PILOT_BOX_WITH_LOGO_INNER()

    CLUSTER_BOX_WITH_LOGO()
        CLUSTER_CTRL("Cluster\nController")
        CLUSTER_NODES("Cluster\nNode")
    END_CLUSTER_BOX_WITH_LOGO()

    FIVEG_BOX_WITH_LOGO()
        FIVEG_CTRL("5G\nController")
    END_FIVEG_BOX_WITH_LOGO()
END_REMOTE_INFRA_BOX()
